// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvrzheu11PMPLe0m3y_5U70GOkT1MomBA',
    appId: '1:632266441497:android:d9412e444ad4a360d7bb88',
    messagingSenderId: '632266441497',
    projectId: 'flutter-cart-vai',
    storageBucket: 'flutter-cart-vai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADOCt3mmexWd81qxQfWM7EBXZMJ_W3bb0',
    appId: '1:632266441497:ios:4f411fca7c798a45d7bb88',
    messagingSenderId: '632266441497',
    projectId: 'flutter-cart-vai',
    storageBucket: 'flutter-cart-vai.firebasestorage.app',
    iosBundleId: 'com.example.cleanArch2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADOCt3mmexWd81qxQfWM7EBXZMJ_W3bb0',
    appId: '1:632266441497:ios:4f6cf755bd16d736d7bb88',
    messagingSenderId: '632266441497',
    projectId: 'flutter-cart-vai',
    storageBucket: 'flutter-cart-vai.firebasestorage.app',
    iosBundleId: 'ahay',
  );
}
